enter_accept = true
filter_mode_shell_up_key_binding = "session"
style = "compact"
workspaces = true
show_help = false
show_tabs = false
keymap_mode = "vim-insert"

[keys]
scroll_exits = false

[sync]
records = true
