# gruvbox catppuccin
[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.normal]
black = "#141617"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#a89984"

[colors.bright]
black = "#7c6f64"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#a89984"
