# gruvbox soft dark
[colors.primary]
background = "#32302f"
foreground = "#d4be98"

[colors.normal]
black = "#7c6f64"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#a89984"

[colors.bright]
black = "#7c6f64"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#a89984"
